### ISSUE TITLE
BackUp and Restore

### ISSUE THREAD

**Issue by ahammadshawki8** [ahammadshawki8/Hospital-Management-System#2]
The backup and restore functionality might not work on other devices as I use `MAIN_FILE` variable equals to my device's folder name in `constants.py` file. So, it will be nice if someone can change it and use `os.cwd` command to grab the current file.

**Comment by mash-97** [comment]
OO.. Bro, you're awesome! 

I was trying to find some simple issues to start learning collaborative work. 
I made a pull request check if works.
I used `os.getcwd()` instead of `os.cwd` to get the current directory.
Hope it works!

**Comment by ahammadshawki8** [comment]
Hmm, I've checked the pr. Thanks for keeping an interest in my project.
